name: smiles-gpt
channels:
  - pytorch
  - anaconda
  - conda-forge
  - plotly
dependencies:
  - python=3.8
  - pip
  - pandas
  - rdkit
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.0
  - plotly
  - optuna
  - scikit-learn
  - pip:
    - tokenizers
    - adapter-transformers
    - pytorch-lightning
    - bertviz
    - selfies
